# Generated by Django 4.2 on 2024-03-06 13:50

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_menucategory_options_alter_menuitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="menu_items",
                to="menu.menucategory",
            ),
        ),
        migrations.AlterField(
            model_name="menuitem",
            name="is_available",
            field=models.BooleanField(
                blank=True, default=False, null=True, verbose_name="Avaialibilty Status"
            ),
        ),
        migrations.AlterField(
            model_name="menuitemimage",
            name="image",
            field=models.ImageField(
                max_length=255, upload_to=menu.models.menu_image_path
            ),
        ),
    ]
