# Generated by Django 4.2 on 2024-03-07 00:26

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_category_alter_menuitem_is_available_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='name', unique=True),
        ),
    ]
