# Generated by Django 4.2 on 2024-03-07 00:52

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_menuitem_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_1',
            field=models.ImageField(default='', max_length=255, upload_to=menu.models.menu_image_path, verbose_name='Image 1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_2',
            field=models.ImageField(default='', max_length=255, upload_to=menu.models.menu_image_path, verbose_name='Image 2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=menu.models.menu_image_path, verbose_name='Image 3'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_promoted',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Promotion Status'),
        ),
        migrations.DeleteModel(
            name='MenuItemImage',
        ),
    ]
