# Generated by Django 4.2 on 2024-03-07 01:20

from django.db import migrations, models
import django.db.models.deletion
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_menuitem_image_1_menuitem_image_2_menuitem_image_3_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='menuitem',
            name='image_3',
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='is_promoted',
            field=models.BooleanField(default=False, verbose_name='Promotion Status'),
        ),
        migrations.CreateModel(
            name='MenuItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=menu.models.menu_image_path)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Menu Image',
                'verbose_name_plural': 'Menu Images',
            },
        ),
    ]
