# Generated by Django 4.2 on 2024-03-07 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_menuitem_image_1_remove_menuitem_image_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='calories',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
