# Generated by Django 4.2 on 2024-03-07 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_alter_menuitem_calories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Avaialibilty Status'),
        ),
    ]
