# Generated by Django 4.2 on 2024-03-08 03:59

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_menuitem_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='menucategory',
            name='image',
            field=models.ImageField(default='', max_length=255, upload_to=menu.models.category_image_path),
            preserve_default=False,
        ),
    ]
