# Generated by Django 4.2 on 2024-03-08 04:29

from django.db import migrations, models
import menu.models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_menucategory_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image_1',
            field=models.ImageField(default='', max_length=255, upload_to=menu.models.menu_image_path),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_2',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=menu.models.menu_image_path),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='image_3',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=menu.models.menu_image_path),
        ),
        migrations.DeleteModel(
            name='MenuItemImage',
        ),
    ]
